import defaultTheme from 'tailwindcss/defaultTheme';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    theme: {
        extend: {
            colors: {
                "outline": "#8c909f",
                "on-secondary": "#002682",
                "primary-container": "#4d8eff",
                "on-error-container": "#ffdad6",
                "tertiary-container": "#8083ff",
                "on-tertiary": "#1000a9",
                "on-secondary-container": "#b2c0ff",
                "on-tertiary-fixed": "#07006c",
                "surface-container-high": "#2a2a2c",
                "secondary-fixed-dim": "#b7c4ff",
                "surface-tint": "#adc6ff",
                "surface-bright": "#39393b",
                "on-secondary-fixed-variant": "#0039b5",
                "outline-variant": "#424754",
                "primary-fixed-dim": "#adc6ff",
                "error-container": "#93000a",
                "tertiary-fixed-dim": "#c0c1ff",
                "secondary-fixed": "#dce1ff",
                "on-primary-fixed": "#001a42",
                "secondary": "#b7c4ff",
                "primary-fixed": "#d8e2ff",
                "on-tertiary-container": "#0d0096",
                "on-background": "#e5e1e4",
                "background": "#131315",
                "on-primary-container": "#00285d",
                "on-error": "#690005",
                "secondary-container": "#0040cb",
                "tertiary-fixed": "#e1e0ff",
                "surface-container": "#201f22",
                "surface-container-lowest": "#0e0e10",
                "error": "#ffb4ab",
                "surface-variant": "#353437",
                "on-primary": "#002e6a",
                "primary": "#adc6ff",
                "surface": "#131315",
                "inverse-surface": "#e5e1e4",
                "surface-dim": "#131315",
                "inverse-on-surface": "#313032",
                "on-secondary-fixed": "#001551",
                "on-surface": "#e5e1e4",
                "tertiary": "#c0c1ff",
                "inverse-primary": "#005ac2",
                "on-tertiary-fixed-variant": "#2f2ebe",
                "on-primary-fixed-variant": "#004395",
                "on-surface-variant": "#c2c6d6",
                "surface-container-highest": "#353437",
                "surface-container-low": "#1c1b1d"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "unit": "4px",
                "container-max": "1440px",
                "gutter": "24px",
                "sm": "8px",
                "xs": "4px",
                "md": "16px",
                "2xl": "48px",
                "xl": "32px",
                "lg": "24px"
            },
            fontFamily: {
                "sans": ["Inter", ...defaultTheme.fontFamily.sans],
                "headline-sm": ["Inter"],
                "display-lg": ["Inter"],
                "display-lg-mobile": ["Inter"],
                "body-sm": ["Inter"],
                "body-base": ["Inter"],
                "label-caps": ["Inter"],
                "mono-code": ["JetBrains Mono"]
            },
            fontSize: {
                "headline-sm": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "display-lg-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "body-sm": ["14px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" }],
                "body-base": ["16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }],
                "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
                "mono-code": ["13px", { "lineHeight": "20px", "fontWeight": "400" }]
            }
        },
    },
    plugins: [],
}
